### ISSUE TITLE
Implement unpacking several layers to the same dir with emulated whiteout processing

### ISSUE THREAD

**Issue by erikh** [box-builder/tarutil#16]
What should happen is:

```
/layer1.tar
/layer2.tar
```

`layer1.tar` is unpacked, revealing the first layer. Overlay whiteouts are ignored during this first processing step.

`layer2.tar` is unpacked. As whiteout files appear, we **delete the file from the unpacked filesystem from the first layer**. This will allow us to get vfs-like behavior without doing a bunch of unpack hackery.

This can be done by mapping the filesystem tree as the tarfiles are read, and then as the >N layers appear, removing the files/mapped files as whiteouts appear. This should also allow re-adds to work: if there was a third layer that added a file that was whiteout removed, it can add the file back.

**Comment by unclejack** [comment]
How is this different from what we have right now in UnpackTar? That function simply unpacks a layer and processes all whiteouts. It can be called sequentially to process multiple layers to extract them in a given directory.

**Comment by erikh** [comment]
I don't want the whiteout files at all, just the processing of the deletions on the filesystem.
